USE [KARAT_TEST]
GO

/****** Object:  Index [PK_Karat_Labels]    Script Date: 15.12.2024 20:41:57 ******/
ALTER TABLE [dbo].[Karat_Labels] ADD  CONSTRAINT [PK_Karat_Labels] PRIMARY KEY CLUSTERED 
(
	[lbCode] ASC,
	[lbMaterial] ASC
)
GO

CREATE NONCLUSTERED INDEX [IX_E_CS_MFDUNIT_DETAILS] ON [dbo].[E_CS_MFDUNIT_DETAILS]
(
	[MFDUNIT_ID] ASC,
	[MATERIAL] ASC
)
GO

ALTER TABLE [dbo].[E_CS_MFDUNIT_CUSTOM] ADD  CONSTRAINT [PK_E_CS_MFDUNIT_CUSTOM] PRIMARY KEY CLUSTERED 
(
	[MFDUNIT_ID] ASC
)
GO





